[project]
name = "ai-agent-based-credit-review-support-system-with-bedrock"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.43.93",
    "langgraph>=1.2.11",
    "langgraph-checkpoint-sqlite>=3.1.1",
    "pgvector>=0.5.0",
    "psycopg[binary]>=3.3.5",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "scikit-learn>=1.9.1",
    "sentence-transformers>=6.0.1",
]
